### ISSUE TITLE
Do not use Array.forEach

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#56]
In `.map()` and `.filter()` we use `.forEach` but we can't break on error, so better to iterate with loops.

**Comment by nechaido** [comment]
@tshemsedinov the only reason for this is synchronous functions in chains, because with asynchronous functions in loop it will anyway only add function calls to the queue and will execute all of them after the loop (due to "run-to-completion" used in JavaScript).
Example:
```js
'use strict'

let errored = false;

let syncFunc = (i, callback) => {
  console.log(i);
  if (i === 2) {
    return callback(new Error('Some error'));
  }
  callback(null, true);
};

let asyncFunc = (i, callback) => {
  setImmediate(syncFunc, i, callback);
};

console.log('Sync functions:');

for (let i = 0; i < 5; i++) {
  syncFunc(i, (err, data) => {
    if (err) errored = true;
    console.error(err, data);
  });
  if (errored) break;
}

console.log('End sync');

errored = false;

console.log('Async functions:');

for (let i = 0; i < 5; i++) {
  asyncFunc(i, (err, data) => {
    if (err) errored = true;
    console.error(err, data);
  });
  if (errored) break;
}
```
Output:
```js
Sync functions:
0
null true
1
null true
2
Error: Some error
    at syncFunc (/home/nechaido/test.js:8:21)
    at Object.<anonymous> (/home/nechaido/test.js:20:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9) undefined
End sync
Async functions:
0
null true
1
null true
2
Error: Some error
    at Immediate.syncFunc (/home/nechaido/test.js:8:21)
    at runCallback (timers.js:670:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5) undefined
3
null true
4
null true
```

**Comment by tshemsedinov** [comment]
Loop `for` just faster iterate arrays then `.forEach` so it will faster put tasks to queue. @nechaido

**Comment by DzyubSpirit** [comment]
`metasync.flow` uses `Array.forEach` now [here](https://github.com/metarhia/MetaSync/blob/master/lib/flow.js#L51)
